# -*- coding: utf-8 -*-
"""CodSoft_task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1psRw_csLYMgPZ2VcDmKRrybBVH9tmcE-
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

df=pd.read_csv("tested.csv")

df

df.fillna(df.median(), inplace=True)

df

X = df.drop('Survived', axis=1)
y = df['Survived']

dummies = pd.get_dummies(X.Sex)
dummies.head(3)

X = pd.concat([X,dummies],axis='columns')
X.head(3)

X.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
X.head()

X.drop(['Sex','male'],axis='columns',inplace=True)
X.head(3)

X.columns[X.isna().any()]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=12)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

logreg = LogisticRegression(random_state=12)
rf = RandomForestClassifier(random_state=12)
svm = SVC(probability=True, random_state=12)

ensemble_model = VotingClassifier(estimators=[('logreg', logreg), ('rf', rf), ('svm', svm)], voting='soft')

ensemble_model.fit(X_train_scaled, y_train)

y_pred = ensemble_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:\n", classification_rep)

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

model.fit(X_train,y_train)

model.score(X_test,y_test)

model.predict(X_test[0:10])

model.predict_proba(X_test[:10])

from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)